// <auto-generated />
namespace StockControl.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updatev10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatev10));
        
        string IMigrationMetadata.Id
        {
            get { return "201906290908507_Updatev1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
